### ISSUE TITLE
Clarify copyright

### ISSUE THREAD

**Issue by jorgesumle** [AlmasB/CV#1]
I was wondering what's the license of the content in this repository. One of the fonts you include appears to be copyrighted, and it doesn't have your name:

> Copyright (c) Jos Buivenga, 2004. All rights reserved.

It would make it easier for people to know whether we can safely base upon the design of your curriculum or not. I'm worried about copyright restrictions.

**Comment by AlmasB** [comment]
Thank you for this. I’ll double check the tex file, but I think the fonts
are not even used. If that is the case, I’ll remove them and clarify the
license.

**Comment by AlmasB** [comment]
All updated. The fonts are not used in the current version of the tex file, hence removed. Added MIT
